worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    upstream daphne {
        server web:8000 fail_timeout=0;
    }

    sendfile on;
    keepalive_timeout 65;

    server_tokens off;
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Redirect all HTTP traffic to HTTPS
    server {
        listen 80;
        server_name ttbg.co.uk www.ttbg.co.uk;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name ttbg.co.uk www.ttbg.co.uk;

        ssl_certificate /etc/letsencrypt/live/ttbg.co.uk/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/ttbg.co.uk/privkey.pem;

        location / {
            proxy_pass http://daphne;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /ws/ {
            proxy_pass http://daphne;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            alias /app/game_site/staticfiles/;
        }
    }

    include servers/*;
}
