# Generated by Django 5.2.13 on 2026-05-12 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5)),
                ('piece_type', models.CharField(choices=[('queen', 'Queen Bee'), ('ant', 'Soldier Ant'), ('spider', 'Spider'), ('beetle', 'Beetle'), ('grasshopper', 'Grasshopper')], max_length=20)),
                ('move_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('lobby', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_state', to='hive.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='LobbyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ready', models.BooleanField(default=False)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive.lobby')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobbyplayer_hive', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lobby',
            name='players',
            field=models.ManyToManyField(related_name='lobby_hive', through='hive.LobbyPlayer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='lobbyplayer',
            constraint=models.UniqueConstraint(fields=('lobby', 'player'), name='unique_player_per_hive_lobby'),
        ),
    ]
