# Generated by Django 5.2.13 on 2026-09-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='ladybug_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='mosquito_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='pillbug_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='piece_type',
            field=models.CharField(choices=[('queen', 'Queen Bee'), ('ant', 'Soldier Ant'), ('spider', 'Spider'), ('beetle', 'Beetle'), ('grasshopper', 'Grasshopper'), ('mosquito', 'Mosquito'), ('ladybug', 'Ladybug'), ('pillbug', 'Pillbug')], max_length=20),
        ),
    ]
